version: 2.1

orbs:
  node: circleci/node@3.0.0

aliases:
  - &docker
    - image: circleci/openjdk:8-jdk-node-browsers

  - &environment
    TZ: /usr/share/zoneinfo/America/Los_Angeles

jobs:
  build:
    docker: *docker
    environment: *environment

    steps:
      - checkout
      - run:
        name: Install packages
        command: npm install
      - run:
          name: Build
          command: npm run build
